export const skillsData = {
  Languages: ['Java', 'JavaScript', 'Python'],
  'Frameworks & Platforms': [
    'Jakarta EE',
    'Spring Boot',
    'JPA',
    'Hibernate',
    'JUnit',
    'NodeJS',
    'ExpressJs',
    'Flask',
  ],
  Database: ['MS SQL', 'Mongo', 'Postgres', 'MySQL'],
  Tools: [
    'Frida',
    'Burp Suite',
    'OWASP ZAP',
    'SQLMap',
    'Nmap',
    'Wireshark',
    'Drozer',
    'ADB',
    'MobSF',
  ],
  'DevSecOps & Integration': [
    'Gitlab CI/CD',
    'Docker',
    'SAST/DAST integration',
    'Jenkins',
  ],
  Techniques: [
    'Reverse Engineering',
    'Threat Emulation',
    'Dynamic Instrumentation',
    'Secure Coding',
    'Code review',
  ],
  'Methodologies & Standards': [
    'OWASP Top 10',
    'MITRE ATT&CK',
    'SANS Top 25',
    'PTES',
  ],
};
